name: Build Vial firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4

      - name: Checkout vial-qmk
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          path: vial-qmk
          submodules: recursive

      - name: Copy keyboard into vial-qmk
        run: |
          mkdir -p vial-qmk/keyboards/cornev3
          cp -r cornev3/* vial-qmk/keyboards/atom47/

      - name: Install QMK CLI
        run: |
          python3 -m pip install --user qmk
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup QMK
        run: |
          qmk setup -y -H vial-qmk

      - name: Build firmware
        working-directory: vial-qmk
        run: |
          qmk compile -kb cornev3 -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: cornev3-vial-firmware
          path: |
            vial-qmk/*.uf2
            vial-qmk/*.hex
            vial-qmk/*.bin
